server:
  port: 8080

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: user
          uri: lb://USER
          predicates:
            - Path=/user-service/**
          filters:
            - PrefixPath=/v1
            - RewritePath=/user/?(?<segment>.*), /$\{segment}
            - ExceptionHandlerFilter
            - AuthorizationHeaderFilter

token:
  secret-key: ${SECRET_KEY}
