token:
  secret-key: ${SECRET_KEY}
  access-token-expire-time: ${ACCESS_TOKEN_RENEW_HOUR}
  refresh-token-renew-hour: ${REFRESH_TOKEN_RENEW_HOUR}

jasypt:
  encrypt-key: ${JASYPT_ENCRYPT_KEY}
  algorithm: ${JASYPT_ALGORITHM}
