name: daehwa discovery api CI / CD
on:
  push:
    branches: ['main']
    paths:
      - discovery/**
      - .github/workflows/discovery-dev.yml

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Java JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'
          cache: 'gradle'

      - name: Build with gradle
        run: ./gradlew clean discovery:build -x test

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: rkdl0829/discovery-service
          tags: |
            type=raw,value=test
            type=raw,value=${{ github.run_number }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./user/Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          push: true
