name: daehwa api CI / CD
on:
  push:
    branches: ['main']
    paths:
      - user/**
      - core/**
      - .github/workflows/user-dev.yml

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Java JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'
          cache: 'gradle'

      - name: Build with gradle
        run: |
          ./gradlew clean
          ./gradlew build -x test
